# Implementing a 1D CNN
This Notebook serves as a beginner-friendly guide to understanding and implementing a 1D Convolutional Neural Network (CNN) in Python. The notebook breaks down the key components of CNNs, including convolution, ReLU activation, and pooling, into separate functions. You are encouraged to complete these functions step by step, gaining practical experience in building neural network layers, and link theory and practice. 
The ideas behind this implementation applies to all kinds of convolution (1D, 2D, 3D), but we stick to 1D for simplicity of the code.

## Convolution:

The `apply_convolution` function is designed to perform convolution on a 1D input (with possibly many channels) using a set of given filters. Convolution is a fundamental operation in convolutional neural networks (CNNs), where filters are applied to input data to extract features. The purpose of this function is to provide hands-on experience in implementing the convolution operation supporting a variable stride.

### Parameters:
- **input_data:** A numpy array representing the input data. It is expected to be 2D array with dimensions (num channels, input length).
- **filters:** A list of 2D numpy arrays representing the filters.
- **stride:** An integer indicating the step size or stride of the convolution operation. The default value is 1, meaning the filters move one element at a time.

### Returns:
- **output:** A 3D numpy array representing the result of the convolution. The dimensions of the output are determined by the number of filters and the length of the resulting convolved sequence.

### Function Logic:
1. The function begins by ensuring that the input data and filters have compatible dimensions. The input data must be either 1D (in case the input has only one chanel) or 2D, and the filters must be 2D.

2. An empty array (`output`) is initialized to store the convolution result.

3. The function calculates the length of the output based on the input data, filter dimensions, and the specified stride.

4. A loop iterates through the input data, applying convolution with the specified stride. The result is computed using element-wise multiplication between the filter and the corresponding portion of the input data, followed by summation along both axes (e.g., axis=(1, 2)).

5. The final output is a 2D numpy array representing the convolution result.

You are expected to complete the function by implementing the convolution operation with the given filters and handling the input data. You should pay attention to the stride parameter, ensuring that the filters move with the specified step size. The completed function will be a crucial building block for creating a convolutional layer in a neural network.

**Simpler variation:**
You can build a simpler approach first by ignoring the stride and assuming it is always 1.

In [81]:
# Import necessary libraries
import numpy as np

# Function 1: Convolution
def apply_convolution(input_data, filters, stride=1):
    """
    Apply convolution on a 1D or 2D input using given filters.

    Parameters:
    - input_data: 2D numpy array, the input data
    - filters: List of 2D numpy arrays, representing the filters
    - stride: Integer, the stride of the convolution operation

    Returns:
    - output: 2D numpy array, the result of convolution
    """

    # If input_data is 2D, ensure filters are the right shape
    assert all(f.shape[0] == input_data.shape[0] for f in filters), "Filter dimensions must match input data dimensions"

    # Initialize an empty array to store the convolution result
    output_length = (input_data.shape[1] - filters[0].shape[1]) // stride + 1
    num_filters = len(filters)
    output = np.zeros((num_filters, output_length))

    # Perform convolution with the specified stride
    for i in range(output_length):
        output[:, i] = np.sum(input_data[:, i * stride:i * stride + filters[0].shape[1]] * filters, axis=(1, 2))

    return output





## Pooling:

The `apply_pooling` function is designed to perform 1D max-pooling. Pooling is a crucial operation in convolutional neural networks (CNNs) that helps reduce the spatial dimensions of the input, capturing important features while reducing computational complexity. Here you need to implement the pooling operation.

### Parameters:
- **input_data:** A numpy array representing the input data.
- **pool_size:** An integer indicating the size of the pooling window. It determines how many elements are considered in each pooling operation.
- **stride:** An integer indicating the step size or stride of the pooling operation. The default value is 1, meaning the pooling window moves one element at a time.

### Returns:
- **result:** A numpy array representing the result after pooling. The dimensions of the result are determined by the number of rows in the input data and the length of the resulting pooled sequence.

### Function Logic:

1. The output length after pooling is calculated based on the input data dimensions, pool size, and the specified stride.

2. An empty array (`result`) is initialized to store the pooling result. The dimensions of this array are determined by the number of rows in the input data and the calculated output length.

3. A loop iterates through the input data, applying 1D pooling with the specified stride. The maximum value within each pooling window is computed using the `np.max` function along axis 1.

4. The final output is a 1D or 2D numpy array representing the result after pooling.

You are expected to complete the function by implementing the 1D pooling operation with the given pool size and stride. The completed function will be an essential component in building a pooling layer for a neural network, aiding in feature extraction and dimensionality reduction. 
**Simpler variation:**
You can build a simpler approach first by ignoring the stride and assuming it is always 1.

In [82]:
# Function 2: 1D Pooling
def apply_pooling(input_data, pool_size, stride=1):
    """
    Apply 1D pooling on the input data.

    Parameters:
    - input_data: 2D numpy array, the input data
    - pool_size: Integer, size of the pooling window
    - stride: Integer, the stride of the pooling operation

    Returns:
    - result: 2D numpy array, the result after pooling
    """
    # Ensure the input is a 1D or 2D array
    assert input_data.ndim in [1, 2], "Input data must be 1D or 2D"

    # Calculate the output length after pooling
    output_length = (input_data.shape[1] - pool_size) // stride + 1

    # Initialize an empty array to store the pooling result
    result = np.zeros((input_data.shape[0], output_length))

    # Perform 1D pooling with the specified stride
    for i in range(output_length):
        result[:, i] = np.max(input_data[:, i * stride:i * stride + pool_size], axis=1)

    return result





## ReLU
In the function below you need to apply the ReLU activation funtion to a given input. This is just one line of code.

In [83]:
# Function 3: ReLU Activation
def apply_relu(input_data):
    """
    Apply ReLU activation on the input data.

    Parameters:
    - input_data: 2D numpy array, the input data

    Returns:
    - result: 2D numpy array, the result after applying ReLU
    """
    # Apply ReLU activation element-wise
    result = np.maximum(0, input_data)

    return result



# 1D CNN:

The `one_dimensional_cnn` function is designed to create a 1D Convolutional Neural Network (CNN) with two convolutional layers, ReLU activation, and pooling. This function should allow you to implement and understand the composition of a simple CNN architecture, combining convolution, activation, and pooling layers.

### Parameters:
- **input_data:** A numpy array representing the input data. It should be a 2D array.
- **filters_layer1:** A list of 2D numpy arrays representing the filters for the first convolutional layer.
- **filters_layer2:** A list of 2D numpy arrays representing the filters for the second convolutional layer.
- **pool_size:** An integer indicating the size of the pooling window. It determines how many elements are considered in each pooling operation.
- **conv_stride:** An integer indicating the stride of the convolution operation. The default value is 1.
- **pool_stride:** An integer indicating the stride of the pooling operation. The default value is 1.

### Returns:
- **output:** A 2D numpy array representing the final output of the CNN after the application of convolution, ReLU activation, and pooling.

### Function Logic:
1. The function should start by applying convolution and ReLU activation for the first layer (`layer1_output`), followed by 1D pooling (`layer1_output_pooled`).

2. Then, it should apply convolution and ReLU activation for the second layer (`layer2_output`), followed by 1D pooling (`layer2_output_pooled`).

3. The final output (`layer2_output_pooled`) will represent the result of the complete CNN architecture.

4. Print the intermediate steps to see the process between operations.


In [84]:

# Function 4: 1D CNN
def one_dimensional_cnn(input_data, filters_layer1, filters_layer2, pool_size, conv_stride=1, pool_stride=1):
    """
    Create a 1D CNN with two convolutional layers, ReLU activation, and pooling.

    Parameters:
    - input_data: 2D numpy array, the input data
    - filters_layer1: List of 2D numpy arrays, filters for the first convolutional layer
    - filters_layer2: List of 2D numpy arrays, filters for the second convolutional layer
    - pool_size: Integer, size of the pooling window

    Returns:
    - output: 2D numpy array, the final output of the CNN
    """
    # Apply convolution and ReLU activation for the first layer
    layer1_output = apply_convolution(input_data, filters_layer1, conv_stride)
    layer1_output_relu = apply_relu(layer1_output)
    layer1_output_pooled = apply_pooling(layer1_output_relu, pool_size, pool_stride)

    # Apply convolution and ReLU activation for the second layer
    layer2_output = apply_convolution(layer1_output_pooled, filters_layer2, conv_stride)
    layer2_output_relu = apply_relu(layer2_output)
    layer2_output_pooled = apply_pooling(layer2_output_relu, pool_size, pool_stride)

    np.set_printoptions(precision=2, suppress=True)
    print(f"Input data: {input_data}\n")
    print(f"Output convolution 1:\n{layer1_output}")
    print(f"ReLU 1:\n{layer1_output_relu}")
    print(f"Pooling 1:\n{layer1_output_pooled}\n")
    print(f"Output convolution 2:\n{layer2_output}")
    print(f"ReLU 2:\n{layer2_output_relu}")
    print(f"Pooling 2:\n{layer2_output_pooled}\n")

    return layer2_output_pooled



Now we can create some input parameters and call the function.
For the sample parameters below, your output should be: [[7. 7. 0. 1. 1.]]

In [85]:
# Example Usage
input_data = np.array([[1, 5, 3, 7, 5, 3, 5, 6, 9, 1]])  # Example 2D input
filters_layer1 = [np.array([[1, -1, 1]]),
                  np.array([[1, -3, 2]])]
filters_layer2 = [np.array([[-2, 1], [2, -1]])]
pool_size = 2

output = one_dimensional_cnn(input_data, filters_layer1, filters_layer2, pool_size)
print("Final Output:", output)

Input data: [[1 5 3 7 5 3 5 6 9 1]]

Output convolution 1:
[[ -1.   9.   1.   5.   7.   4.   8.  -2.]
 [ -8.  10.  -8.  -2.   6.   0.   5. -19.]]
ReLU 1:
[[ 0.  9.  1.  5.  7.  4.  8.  0.]
 [ 0. 10.  0.  0.  6.  0.  5.  0.]]
Pooling 1:
[[ 9.  9.  5.  7.  7.  8.  8.]
 [10. 10.  0.  6.  6.  5.  5.]]

Output convolution 2:
[[ 1.  7. -9. -1.  1. -3.]]
ReLU 2:
[[1. 7. 0. 0. 1. 0.]]
Pooling 2:
[[7. 7. 0. 1. 1.]]

Final Output: [[7. 7. 0. 1. 1.]]
